### ISSUE TITLE
Graceful notification of microphone activation failure

### ISSUE THREAD

**Issue by shengchalover** [Cay-Zhang/SwiftSpeech#1] opened 2020-08-14 08:40 UTC
Hi!

I've encountered an exception due to a bug in [iOS 14 beta 4 + AirPods](https://www.reddit.com/r/iOS14Beta/comments/i4tenq/ios_14_beta_4_and_airpods_pro/) that breaks (on software level, hopefully) mic on AirPods. In system apps (iMessage, Recorder ...) the issue prevents voice recording/recognition from working but it does not crash an app. In case of SwiftSpeech, the app crashes with uncaught exception.

Is is possible to catch such a failure and gracefully pass notification with the error? Or at least prevent the crash.

The log message is:
`Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: IsFormatSampleRateAndChannelCountValid(format)'`

**Comment by Cay-Zhang** [comment] 2020-08-14 08:54
Hi, is the error thrown when you start a recording or during recording?

**Comment by shengchalover** [comment] 2020-08-17 18:17
immediately upon starting the recording

**Comment by Cay-Zhang** [comment] 2020-08-17 18:26
Ok. Will do a quick fix tomorrow to catch the error.

**Comment by Cay-Zhang** [comment] 2020-08-26 11:44
The issue is resolved in [**v0.9.1**](https://github.com/Cay-Zhang/SwiftSpeech/releases/tag/v0.9.1).

> Errors happened during the initialization of the recording session (such as a microphone activation failure) are now sent through resultSubject, so that you can catch them in error handlers of onRecognize.

**Closed by Cay-Zhang** 2020-08-26 11:44 UTC
